<div class="iwd-opc-forgot-main-wrapper" style="display: none;">
    <div class="iwd-opc-forgotpassword">
        <div class="main-opc-forgot-wrapper">
            <div class="forgot-header">
                <?php echo __('FORGOT PASSWORD'); ?>
            </div>
            <form class="form password forget iwd-opc-forgot-form"
                  action="<?php /* @escapeNotVerified */
                  echo $block->getUrl('*/*/forgotpasswordpost') ?>"
                  method="post"
                  id="form-validate"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */
                echo __('* Required Fields') ?>">
                    <div class="field note"><?php /* @escapeNotVerified */
                        echo __('Please enter your email address below. You will receive a link to reset your password.'); ?></div>
                    <div class="field email required">
                        <label for="email_address" class="label"><span><?php /* @escapeNotVerified */
                                echo __('Email Address') ?></span></label>

                        <div class="control">
                            <input type="email" name="email" alt="email" id="email_address" class="input-text"
                                   value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */
                                echo __('Submit') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action back" href="<?php /* @escapeNotVerified */
                        echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */
                                echo __('Go back') ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    // <![CDATA[
    require(['IWD_Opc/js/iwd/iwd_opc', 'jquery'],
        function (iwdOpc, $) {
            var oneStepCheckout = new iwdOpc();
            $(document).ready(oneStepCheckout.init());
        }
    );
    // ]]>
</script>

